import{a as l,S as m,i as c}from"./assets/vendor-f1e580de.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();l.defaults.headers.common["x-api-key"]="live_6vEYdyqrWWmlLRh7wTSmN9YmDqFWmsIhbvPTsjZaX3cBV3miKzP6vjBVaX6xAXlK";async function u(){const o="https://api.thecatapi.com/v1/breeds";try{return(await l.get(o)).data}catch(t){throw console.error("Сталася помилка при отриманні:",t),t}}async function y(o){try{return(await l.get("https://api.thecatapi.com/v1/images/search",{params:{breed_ids:o}})).data}catch(t){throw console.error("Failed to fetch cat by breed:",t),t}}l.defaults.headers.common["x-api-key"]="live_6vEYdyqrWWmlLRh7wTSmN9YmDqFWmsIhbvPTsjZaX3cBV3miKzP6vjBVaX6xAXlK";const f=new m({select:"#selectElement"}),a=document.querySelector(".breed-select"),p=document.querySelector(".cat-info"),i=document.querySelector(".loader-text");document.addEventListener("DOMContentLoaded",async()=>{if(!a){c.error({title:"Ой! Помилка!",message:"Щось зломалось під час отримання інформації",position:"topCenter",timeout:5e3});return}try{i.style.display="block",(await u()).forEach(t=>{const s=document.createElement("option");s.value=t.id,s.textContent=t.name,f.addOption(s)}),a.classList.toggle("hidden")}catch(o){c.error({title:"Ой! Помилка!  ",message:"Щось зломалось під час додавання породи у перелік",position:"topCenter",timeout:5e3}),console.error("Error populating breed select:",o)}finally{i.style.display="none",a.style.visibility="visible"}a.addEventListener("change",async o=>{const t=o.target.value;if(t){i.style.display="block",p.style.display="none";try{const s=await y(t);if(s.length>0){const n=s[0],e=n.breeds[0];p.innerHTML=`
              <h2 class="breed-name">${e.name}</h2>
              <div class="breed-info">
              <div class="breed-img"><img src="${n.url}" alt="${e.name}"></div>
              <div class="desc">
              <p class="label">Description:</p> <p class="desc-text"> ${e.description}</p>
              <p class="label">Temperament:</p> <p class="desc-text"> ${e.temperament}</p>
              </div>
              </div>
          `,i.style.display="none",p.style.display="block"}else c.error({title:"Ой! Помилка!",message:"Схоже, що інформація про цю породу засекречена",position:"topCenter",timeout:5e3}),i.style.display="none"}catch(s){console.error("Error fetching cat data:",s),c.error({title:"Ой! Помилка!",message:"Головний котоексперт не відповідає. Спробуй ще раз",position:"topCenter",timeout:5e3})}}})});
//# sourceMappingURL=commonHelpers.js.map
