import{a,S as p,i as n}from"./assets/vendor-f1e580de.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();a.defaults.headers.common["x-api-key"]="live_6vEYdyqrWWmlLRh7wTSmN9YmDqFWmsIhbvPTsjZaX3cBV3miKzP6vjBVaX6xAXlK";async function u(){const s="https://api.thecatapi.com/v1/breeds";try{return(await a.get(s)).data}catch(t){throw console.error("Сталася помилка при отриманні:",t),t}}async function f(s){try{return(await a.get("https://api.thecatapi.com/v1/images/search",{params:{breed_ids:s}})).data}catch(t){throw console.error("Failed to fetch cat by breed:",t),t}}a.defaults.headers.common["x-api-key"]="live_6vEYdyqrWWmlLRh7wTSmN9YmDqFWmsIhbvPTsjZaX3cBV3miKzP6vjBVaX6xAXlK";const y=new p({select:"#selectElement"}),d=document.querySelector(".breed-select"),l=document.querySelector(".cat-info"),m=document.querySelector(".loader-text");document.addEventListener("DOMContentLoaded",async()=>{if(!d){n.error({title:"Ой! Помилка!",message:"Щось зломалось під час отримання інформації",position:"topCenter",timeout:5e3});return}try{(await u()).forEach(t=>{const o=document.createElement("option");o.value=t.id,o.textContent=t.name,y.addOption(o)})}catch(s){n.error({title:"Ой! Помилка!",message:"Щось зломалось під час додавання породи у перелік",position:"topCenter",timeout:5e3}),console.error("Error populating breed select:",s)}d.addEventListener("change",async s=>{const t=s.target.value;if(t){m.style.display="block",l.style.display="none";try{const o=await f(t);if(o.length>0){const c=o[0],e=c.breeds[0];l.innerHTML=`
              <h2 class="breed-name">${e.name}</h2>
              <div class="breed-info">
              <div class="breed-img"><img src="${c.url}" alt="${e.name}"></div>
              <div class="desc">
              <p class="label">Description:</p> <p class="desc-text"> ${e.description}</p>
              <p class="label">Temperament:</p> <p class="desc-text"> ${e.temperament}</p>
              </div>
              </div>
          `,m.style.display="none",l.style.display="block"}else n.error({title:"Ой! Помилка!",message:"Схоже, що інформація про цю породу засекречена",position:"topCenter",timeout:5e3})}catch(o){console.error("Error fetching cat data:",o),n.error({title:"Ой! Помилка!",message:"Головний котоексперт не відповідає. Спробуй ще раз",position:"topCenter",timeout:5e3})}}})});
//# sourceMappingURL=commonHelpers.js.map
